CREATE DATABASE pokemon;
USE pokemon;


DROP TABLE IF EXISTS pokemon;
DROP TABLE IF EXISTS tipo_pokemon;
DROP TABLE IF EXISTS pokemon_tipo_raw;

CREATE TABLE pokemon_tipo_raw (
    id_raw INT AUTO_INCREMENT PRIMARY KEY,
    nombre_pokemon VARCHAR(80) NOT NULL,
    altura DECIMAL(5,2),
    peso DECIMAL(5,2),
    estado_evolutivo ENUM('BASICO','INTERMEDIO','FINAL') NOT NULL,
    nombre_tipo VARCHAR(50) NOT NULL,
    descripcion_pokemon VARCHAR(255)
);

CREATE TABLE tipo_pokemon (
    id_tipo INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE pokemon (
    id_pokemon INT AUTO_INCREMENT PRIMARY KEY,
    fid_tipo INT NOT NULL,
    nombre VARCHAR(80) NOT NULL,
    altura DECIMAL(5,2),
    peso DECIMAL(5,2),
    estado_evolutivo ENUM('BASICO','INTERMEDIO','FINAL') NOT NULL,
    descripcion VARCHAR(255),
    FOREIGN KEY (fid_tipo) REFERENCES tipo_pokemon(id_tipo)
);

INSERT INTO pokemon_tipo_raw
(nombre_pokemon, altura, peso, estado_evolutivo, nombre_tipo, descripcion_pokemon)
VALUES
('BULBASAUR', 0.70, 6.9, 'BASICO', 'PLANTA', 'TRAS NACER, CRECE ALIMENTÁNDOSE DE LOS NUTRIENTES DE LA SEMILLA QUE LLEVA EN EL LOMO.'),
('IVYSAUR', 1.00, 13.0, 'INTERMEDIO', 'PLANTA', 'CUANDO EL BULBO DE SU ESPALDA CRECE, PARECE PERDER MOVILIDAD.'),
('VENUSAUR', 2.00, 100.0, 'FINAL', 'PLANTA', 'LA PLANTA FLORECE AL ABSORBER ENERGÍA SOLAR.'),
('CHARMANDER', 0.60, 8.5, 'BASICO', 'FUEGO', 'LA LLAMA DE SU COLA INDICA SU ESTADO DE SALUD.'),
('CHARMELEON', 1.10, 19.0, 'INTERMEDIO', 'FUEGO', 'CUANDO SE ENFADA, LA LLAMA DE SU COLA ARDE CON MÁS INTENSIDAD.'),
('CHARIZARD', 1.70, 90.5, 'FINAL', 'FUEGO', 'ESCUPE FUEGO CAPAZ DE FUNDIR ROCAS.'),
('SQUIRTLE', 0.50, 9.0, 'BASICO', 'AGUA', 'SE PROTEGE EN SU CAPARAZÓN Y LANZA AGUA A PRESIÓN.'),
('WARTORTLE', 1.00, 22.5, 'INTERMEDIO', 'AGUA', 'SU COLA ES SÍMBOLO DE LONGEVIDAD.'),
('BLASTOISE', 1.60, 85.5, 'FINAL', 'AGUA', 'DISPARA POTENTES CHORROS DE AGUA DESDE SU CAPARAZÓN.'),
('CATERPIE', 0.30, 2.9, 'BASICO', 'BICHO', 'LIBERA UN FUERTE OLOR PARA REPELER ENEMIGOS.'),
('METAPOD', 0.70, 9.9, 'INTERMEDIO', 'BICHO', 'ENDURECE SU CAPARAZÓN PARA PROTEGERSE.'),
('BUTTERFREE', 1.10, 32.0, 'FINAL', 'BICHO', 'SUS ALAS DESPRENDEN POLVO TÓXICO.'),
('WEEDLE', 0.30, 3.2, 'BASICO', 'BICHO', 'TIENE UN AGUIJÓN VENENOSO EN LA CABEZA.'),
('KAKUNA', 0.60, 10.0, 'INTERMEDIO', 'BICHO', 'PERMANECE CASI INMÓVIL MIENTRAS EVOLUCIONA.'),
('BEEDRILL', 1.00, 29.5, 'FINAL', 'BICHO', 'ATACA CON SUS AGUIJONES VENENOSOS.'),
('PIDGEY', 0.30, 1.8, 'BASICO', 'NORMAL', 'ES DÓCIL Y FÁCIL DE CAPTURAR.'),
('PIDGEOTTO', 1.10, 30.0, 'INTERMEDIO', 'NORMAL', 'DEFIENDE SU TERRITORIO CON AGRESIVIDAD.'),
('PIDGEOT', 1.50, 39.5, 'FINAL', 'NORMAL', 'VUELA A GRAN VELOCIDAD EN BUSCA DE PRESAS.'),
('RATTATA', 0.30, 3.5, 'BASICO', 'NORMAL', 'MUERDE CUALQUIER COSA CON SUS AFILADOS DIENTES.'),
('RATICATE', 0.70, 18.5, 'FINAL', 'NORMAL', 'SUS DIENTES CRECEN CONSTANTEMENTE.'),
('SPEAROW', 0.30, 2.0, 'BASICO', 'NORMAL', 'DE TEMPERAMENTO AGRESIVO.'),
('FEAROW', 1.20, 38.0, 'FINAL', 'NORMAL', 'VUELA GRANDES DISTANCIAS EN BUSCA DE ALIMENTO.'),
('EKANS', 2.00, 6.9, 'BASICO', 'VENENO', 'SE ENROLLA SIGILOSAMENTE PARA ATACAR.'),
('ARBOK', 3.50, 65.0, 'FINAL', 'VENENO', 'SU PATRÓN INTIMIDA A SUS ENEMIGOS.'),
('PIKACHU', 0.40, 6.0, 'BASICO', 'ELECTRICO', 'ESTE INTELIGENTE POKÉMON TUESTA LAS DURAS BAYAS CON ELECTRICIDAD PARA HACERLAS MÁS COMESTIBLES.'),
('RAICHU', 0.80, 30.0, 'FINAL', 'ELECTRICO', 'PUEDE LIBERAR GRANDES CANTIDADES DE ELECTRICIDAD.'),
('SANDSHREW', 0.60, 12.0, 'BASICO', 'TIERRA', 'SE ENROLLA PARA PROTEGERSE.'),
('SANDSLASH', 1.00, 29.5, 'FINAL', 'TIERRA', 'ATACA CON SUS AFILADAS GARRAS.'),
('NIDORANF', 0.40, 7.0, 'BASICO', 'VENENO', 'TIENE GRAN SENSIBILIDAD AUDITIVA.'),
('NIDORINA', 0.80, 20.0, 'INTERMEDIO', 'VENENO', 'SE VUELVE AGRESIVA AL PROTEGER A SUS CRÍAS.'),
('NIDOQUEEN', 1.30, 60.0, 'FINAL', 'VENENO', 'POSEE UNA GRAN FUERZA DEFENSIVA.'),
('NIDORANM', 0.50, 9.0, 'BASICO', 'VENENO', 'DETECTA ENEMIGOS CON SUS OREJAS.'),
('NIDORINO', 0.90, 19.5, 'INTERMEDIO', 'VENENO', 'ATACA CON SU CUERNO VENENOSO.'),
('NIDOKING', 1.40, 62.0, 'FINAL', 'VENENO', 'SU COLA PUEDE DERRIBAR ESTRUCTURAS.'),
('CLEFAIRY', 0.60, 7.5, 'BASICO', 'NORMAL', 'SE DICE QUE VIVE EN LA LUNA.'),
('CLEFABLE', 1.30, 40.0, 'FINAL', 'NORMAL', 'ES MUY SENSIBLE A LOS SONIDOS.'),
('VULPIX', 0.60, 9.9, 'BASICO', 'FUEGO', 'POSEE SEIS COLAS QUE CRECEN CON EL TIEMPO.'),
('NINETALES', 1.10, 19.9, 'FINAL', 'FUEGO', 'SE DICE QUE VIVE MIL AÑOS.'),
('JIGGLYPUFF', 0.50, 5.5, 'BASICO', 'NORMAL', 'DUERME A SUS ENEMIGOS CON SU CANTO.'),
('WIGGLYTUFF', 1.00, 12.0, 'FINAL', 'NORMAL', 'SU CUERPO ES MUY ELÁSTICO.'),
('ZUBAT', 0.80, 7.5, 'BASICO', 'VENENO', 'SE ORIENTA MEDIANTE ULTRASONIDOS.'),
('GOLBAT', 1.60, 55.0, 'FINAL', 'VENENO', 'CHUPA SANGRE DE SUS PRESAS.'),
('ODDISH', 0.50, 5.4, 'BASICO', 'PLANTA', 'SE ENTERRA DURANTE EL DÍA.'),
('GLOOM', 0.80, 8.6, 'INTERMEDIO', 'PLANTA', 'LIBERA UN OLOR DESAGRADABLE.'),
('VILEPLUME', 1.20, 18.6, 'FINAL', 'PLANTA', 'SUS PÉTALOS SON VENENOSOS.'),
('PARAS', 0.30, 5.4, 'BASICO', 'BICHO', 'UN HONGO CRECE SOBRE SU ESPALDA.'),
('PARASECT', 1.00, 29.5, 'FINAL', 'BICHO', 'EL HONGO CONTROLA SU CUERPO.'),
('VENONAT', 1.00, 30.0, 'BASICO', 'BICHO', 'SUS OJOS DETECTAN PRESAS EN LA OSCURIDAD.'),
('VENOMOTH', 1.50, 12.5, 'FINAL', 'BICHO', 'SUS ALAS DISPERSAN POLVO VENENOSO.'),
('DIGLETT', 0.20, 0.8, 'BASICO', 'TIERRA', 'VIVE BAJO TIERRA Y APARECE EN LA SUPERFICIE PARA ALIMENTARSE.');

DROP PROCEDURE IF EXISTS listar_pokemon_tipo_raw;
DROP PROCEDURE IF EXISTS insertar_tipo_pokemon;
DROP PROCEDURE IF EXISTS obtener_tipo_pokemon_por_nombre;
DROP PROCEDURE IF EXISTS insertar_pokemon;

DELIMITER $$

CREATE PROCEDURE listar_pokemon_tipo_raw()
BEGIN
    SELECT 
        id_raw,
        nombre_pokemon,
        altura,
        peso,
        estado_evolutivo,
        nombre_tipo,
        descripcion_pokemon
    FROM pokemon_tipo_raw
    ORDER BY id_raw;
END$$

CREATE PROCEDURE insertar_tipo_pokemon(
    IN p_nombre VARCHAR(50),
    OUT p_id_tipo INT
)
BEGIN
    INSERT INTO tipo_pokemon(nombre)
    VALUES(p_nombre);

    SET p_id_tipo = LAST_INSERT_ID();
END$$

CREATE PROCEDURE obtener_tipo_pokemon_por_nombre(
    IN p_nombre VARCHAR(50),
    OUT p_id_tipo INT
)
BEGIN
    SELECT id_tipo
    INTO p_id_tipo
    FROM tipo_pokemon
    WHERE nombre = p_nombre
    LIMIT 1;
END$$

CREATE PROCEDURE insertar_pokemon(
    OUT p_id_pokemon INT,
    IN p_nombre VARCHAR(80),
    IN p_fid_tipo INT,
    IN p_altura DECIMAL(5,2),
    IN p_peso DECIMAL(5,2),
    IN p_estado_evolutivo ENUM('BASICO','INTERMEDIO','FINAL'),
    IN p_descripcion VARCHAR(255)
)
BEGIN
    INSERT INTO pokemon(nombre, altura, peso, estado_evolutivo, descripcion, fid_tipo)
    VALUES(p_nombre, p_altura, p_peso, p_estado_evolutivo, p_descripcion, p_fid_tipo);

    SET p_id_pokemon = LAST_INSERT_ID();
END$$

DELIMITER ;